import { describe, expect, it } from "vitest";
import {
  carrierOptionsForEvidence,
  evidenceAssignmentsForScene,
  generatedStandaloneHotspotId,
  hotspotOptionsForEvidence,
  moveEvidenceRevealInScene,
  updateEvidenceAssignmentInMarkdown,
  updateEvidenceCarrierInMarkdown,
} from "./evidence-assignment";
import type { InvestigationSceneJson } from "./layout-types";

const markdown = `# Investigation

## Sublocation: Office {#office}

### Hotspot: Desk {#desk}
- **Description:** A messy desk.
- **Evidence Source:** visible
- **Reveals:** [evidence:receipt, topic:witness/rain]

### Hotspot: Terminal {#terminal}
- **Description:** A locked terminal.

### Hotspot: Folder {#folder}
- **Description:** A folder.
- **Reveals:** [evidence:memo]
`;

const carrierMarkdown = `# Investigation

## Sub-location: Inner storage {#inner}
- **Status:** unlocked

[場景：內側倉庫。]

### Hotspot: 法醫初步簡報 {#evidence_source_forensic_prelim_range}
- **Description:** 編輯器產生的隱藏證據來源。
- **Evidence Source:** hidden
- **Scene Source Prompt:** Hidden local evidence source generated by the layout editor; the collected evidence is not visibly readable in the background.
- **Reveals:** [evidence:forensic_prelim_range]

[黑瀨遞出簡報。]

### Hotspot: 後場入口 {#back_entrance}
- **Description:** 通往走廊的入口。
- **Reveals:** [sublocation:corridor]

[相馬往後場看。]

### Character: 黑瀨徹 {#kurose}
- **Role:** 刑警
- **Bio:** 提供程序內可公開的資訊。

#### Topic: 法醫初步簡報 {#forensic_brief}
- **Status:** unlocked

**黑瀨徹**：法醫初步。死亡時間給的是一段範圍。
`;

const scene = {
  type: "investigation",
  id: "investigation_scene_1",
  title: "Test",
  intro: [],
  sublocations: [
    {
      id: "office",
      label: "Office",
      sceneTag: "Office",
      backgroundAssetId: null,
      transitionDialogue: [],
      hotspots: [
        {
          id: "desk",
          label: "Desk",
          description: "A messy desk.",
          evidenceSource: "visible",
          sceneSourcePrompt: null,
          reveals: [
            { kind: "evidence", id: "receipt" },
            { kind: "topic", characterId: "witness", topicId: "rain" },
          ],
          inspectDialogue: [],
          layout: null,
        },
        {
          id: "terminal",
          label: "Terminal",
          description: "A locked terminal.",
          evidenceSource: null,
          sceneSourcePrompt: null,
          reveals: [],
          inspectDialogue: [],
          layout: null,
        },
        {
          id: "folder",
          label: "Folder",
          description: "A folder.",
          evidenceSource: null,
          sceneSourcePrompt: null,
          reveals: [{ kind: "evidence", id: "memo" }],
          inspectDialogue: [],
          layout: null,
        },
      ],
      characters: [],
    },
  ],
  evidenceManifest: [
    {
      id: "receipt",
      name: "Receipt",
      description: "Receipt clue.",
      imageAssetId: "evidence.receipt",
      sourceSublocationId: null,
    },
    {
      id: "memo",
      name: "Memo",
      description: "Memo clue.",
      imageAssetId: "evidence.memo",
      sourceSublocationId: null,
    },
  ],
} satisfies InvestigationSceneJson;

const kuroseCharacter = {
  id: "kurose",
  name: "黑瀨徹",
  role: "刑警",
  bio: "提供程序內可公開的資訊。",
  layout: null,
  topics: [
    {
      id: "forensic_brief",
      label: "法醫初步簡報",
      status: "unlocked",
      reveals: [],
      topicDialogue: [],
    },
  ],
};

const sourceSublocationScene = {
  type: "investigation",
  id: "investigation_scene_source_sublocations",
  title: "Source sublocation test",
  intro: [],
  sublocations: [
    {
      id: "front",
      label: "Front",
      sceneTag: "Front",
      backgroundAssetId: null,
      transitionDialogue: [],
      hotspots: [
        {
          id: "front-door",
          label: "Front door",
          description: "The front door.",
          evidenceSource: null,
          sceneSourcePrompt: null,
          reveals: [],
          inspectDialogue: [],
          layout: null,
        },
      ],
      characters: [],
    },
    {
      id: "corridor",
      label: "Corridor",
      sceneTag: "Corridor",
      backgroundAssetId: null,
      transitionDialogue: [],
      hotspots: [
        {
          id: "access-panel",
          label: "Access panel",
          description: "A maintenance panel.",
          evidenceSource: "visible",
          sceneSourcePrompt: null,
          reveals: [{ kind: "evidence", id: "log" }],
          inspectDialogue: [],
          layout: null,
        },
        {
          id: "evidence_source_log",
          label: "Access log generated source",
          description: "Generated hidden source.",
          evidenceSource: "hidden",
          sceneSourcePrompt: "Generated hidden source.",
          reveals: [{ kind: "evidence", id: "log" }],
          inspectDialogue: [],
          layout: null,
        },
        {
          id: "plain-door",
          label: "Plain door",
          description: "A door without evidence-source metadata.",
          evidenceSource: null,
          sceneSourcePrompt: null,
          reveals: [],
          inspectDialogue: [],
          layout: null,
        },
      ],
      characters: [kuroseCharacter],
    },
  ],
  evidenceManifest: [
    {
      id: "log",
      name: "Access log",
      description: "A corridor access log.",
      imageAssetId: null,
      sourceSublocationId: "corridor",
    },
  ],
} satisfies InvestigationSceneJson;

describe("updateEvidenceAssignmentInMarkdown", () => {
  it("moves evidence to another hotspot while preserving non-evidence reveals", () => {
    const result = updateEvidenceAssignmentInMarkdown(markdown, {
      evidenceId: "receipt",
      hotspotId: "terminal",
    });

    expect(result.changed).toBe(true);
    expect(result.contents).toContain(
      "### Hotspot: Desk {#desk}\n- **Description:** A messy desk.\n- **Evidence Source:** visible\n- **Reveals:** [topic:witness/rain]",
    );
    expect(result.contents).toContain(
      "### Hotspot: Terminal {#terminal}\n- **Description:** A locked terminal.\n- **Reveals:** [evidence:receipt]",
    );
  });

  it("adds evidence to a hotspot that already reveals another evidence item", () => {
    const result = updateEvidenceAssignmentInMarkdown(markdown, {
      evidenceId: "receipt",
      hotspotId: "folder",
    });

    expect(result.contents).toContain(
      "- **Reveals:** [evidence:memo, evidence:receipt]",
    );
  });

  it("detaches evidence and removes an empty Reveals line", () => {
    const result = updateEvidenceAssignmentInMarkdown(markdown, {
      evidenceId: "memo",
      hotspotId: null,
    });

    expect(result.contents).toContain(
      "### Hotspot: Folder {#folder}\n- **Description:** A folder.\n",
    );
    expect(result.contents).not.toContain("- **Reveals:** [evidence:memo]");
  });

  it("throws when the target hotspot does not exist", () => {
    expect(() =>
      updateEvidenceAssignmentInMarkdown(markdown, {
        evidenceId: "receipt",
        hotspotId: "missing",
      }),
    ).toThrow('Hotspot "missing" was not found');
  });

  it("preserves topic reveals for the same evidence while moving hotspot assignment", () => {
    const markdownWithTopicReveal = `${markdown}
### Character: Witness {#witness}
- **Role:** Witness
- **Bio:** Saw the rain.

#### Topic: Rain receipt {#rain_receipt}
- **Status:** unlocked
- **Reveals:** [evidence:receipt]
`;

    const result = updateEvidenceAssignmentInMarkdown(markdownWithTopicReveal, {
      evidenceId: "receipt",
      hotspotId: "terminal",
    });

    expect(result.contents).toContain(
      "### Hotspot: Terminal {#terminal}\n- **Description:** A locked terminal.\n- **Reveals:** [evidence:receipt]",
    );
    expect(result.contents).toContain(
      "#### Topic: Rain receipt {#rain_receipt}\n- **Status:** unlocked\n- **Reveals:** [evidence:receipt]",
    );
  });
});

describe("updateEvidenceCarrierInMarkdown", () => {
  it("moves evidence from generated standalone hotspot to a character topic and removes the empty generated hotspot", () => {
    const result = updateEvidenceCarrierInMarkdown(carrierMarkdown, {
      evidenceId: "forensic_prelim_range",
      evidenceName: "法醫初步死亡範圍",
      sourceSublocationId: "inner",
      carrier: {
        kind: "topic",
        sublocationId: "inner",
        characterId: "kurose",
        topicId: "forensic_brief",
      },
    });

    expect(result.changed).toBe(true);
    expect(result.removedStandaloneHotspotIds).toEqual([
      "evidence_source_forensic_prelim_range",
    ]);
    expect(result.contents).not.toContain(
      "### Hotspot: 法醫初步簡報 {#evidence_source_forensic_prelim_range}",
    );
    expect(result.contents).toContain(
      "#### Topic: 法醫初步簡報 {#forensic_brief}\n- **Status:** unlocked\n- **Reveals:** [evidence:forensic_prelim_range]",
    );
    expect(result.contents).toContain("### Hotspot: 後場入口 {#back_entrance}");
  });

  it("creates a hidden standalone hotspot in the source sublocation", () => {
    const result = updateEvidenceCarrierInMarkdown(carrierMarkdown, {
      evidenceId: "new_record",
      evidenceName: "新紀錄",
      sourceSublocationId: "inner",
      carrier: { kind: "standalone_hotspot", sublocationId: "inner" },
    });

    expect(result.createdStandaloneHotspotId).toBe(
      "evidence_source_new_record",
    );
    expect(result.contents).toContain(
      "### Hotspot: 新紀錄 {#evidence_source_new_record}\n- **Description:** 編輯器產生的隱藏證據來源。\n- **Evidence Source:** hidden\n- **Scene Source Prompt:** Hidden local evidence source generated by the layout editor; the collected evidence is not visibly readable in the background.\n- **Reveals:** [evidence:new_record]",
    );
  });

  it("does not delete authored hotspots after moving their final evidence reveal", () => {
    const authored = carrierMarkdown.replace(
      "- **Reveals:** [sublocation:corridor]",
      "- **Reveals:** [sublocation:corridor, evidence:new_record]",
    );
    const result = updateEvidenceCarrierInMarkdown(authored, {
      evidenceId: "new_record",
      evidenceName: "新紀錄",
      sourceSublocationId: "inner",
      carrier: {
        kind: "topic",
        sublocationId: "inner",
        characterId: "kurose",
        topicId: "forensic_brief",
      },
    });

    expect(result.contents).toContain("### Hotspot: 後場入口 {#back_entrance}");
    expect(result.contents).toContain("- **Reveals:** [sublocation:corridor]");
  });

  it("preserves an existing standalone hotspot when assigning it again", () => {
    const result = updateEvidenceCarrierInMarkdown(carrierMarkdown, {
      evidenceId: "forensic_prelim_range",
      evidenceName: "法醫初步死亡範圍",
      sourceSublocationId: "inner",
      carrier: { kind: "standalone_hotspot", sublocationId: "inner" },
    });

    expect(result.changed).toBe(false);
    expect(result.createdStandaloneHotspotId).toBeNull();
    expect(result.removedStandaloneHotspotIds).toEqual([]);
    expect(result.contents).toBe(carrierMarkdown);
    expect(result.contents).toContain("[黑瀨遞出簡報。]");
  });
});

describe("hotspotOptionsForEvidence", () => {
  it("limits options to hotspots in the evidence source sublocation", () => {
    expect(
      hotspotOptionsForEvidence(
        sourceSublocationScene,
        sourceSublocationScene.evidenceManifest[0],
      ),
    ).toEqual([
      {
        id: "access-panel",
        label: "Access panel",
        sublocationId: "corridor",
        sublocationLabel: "Corridor",
      },
    ]);
  });

  it("omits hotspots that cannot safely reveal evidence", () => {
    const options = hotspotOptionsForEvidence(
      sourceSublocationScene,
      sourceSublocationScene.evidenceManifest[0],
    );

    expect(options.map((option) => option.id)).not.toContain("plain-door");
  });
});

describe("carrierOptionsForEvidence", () => {
  it("lists evidence-capable hotspots, character topics, and standalone creation in the evidence source sublocation", () => {
    expect(
      carrierOptionsForEvidence(
        sourceSublocationScene,
        sourceSublocationScene.evidenceManifest[0],
      ),
    ).toEqual([
      {
        label: "Corridor / Access panel",
        carrier: {
          kind: "hotspot",
          sublocationId: "corridor",
          hotspotId: "access-panel",
        },
      },
      {
        label: "Corridor / 黑瀨徹 / 法醫初步簡報",
        carrier: {
          kind: "topic",
          sublocationId: "corridor",
          characterId: "kurose",
          topicId: "forensic_brief",
        },
      },
      {
        label: "Create standalone hotspot",
        carrier: {
          kind: "standalone_hotspot",
          sublocationId: "corridor",
        },
      },
    ]);
  });

  it("does not list non-source sublocation targets", () => {
    const labels = carrierOptionsForEvidence(
      sourceSublocationScene,
      sourceSublocationScene.evidenceManifest[0],
    ).map((option) => option.label);

    expect(labels).not.toContain("Front / Front door");
  });

  it("does not list generated standalone hotspots as normal carrier targets", () => {
    const labels = carrierOptionsForEvidence(
      sourceSublocationScene,
      sourceSublocationScene.evidenceManifest[0],
    ).map((option) => option.label);

    expect(labels).not.toContain("Corridor / Access log generated source");
    expect(labels).toContain("Create standalone hotspot");
  });
});

describe("generatedStandaloneHotspotId", () => {
  it("uses the evidence_source id convention", () => {
    expect(generatedStandaloneHotspotId("forensic_prelim_range")).toBe(
      "evidence_source_forensic_prelim_range",
    );
  });
});

describe("evidenceAssignmentsForScene", () => {
  it("lists current hotspot assignments for every evidence manifest item", () => {
    expect(evidenceAssignmentsForScene(scene)).toEqual([
      {
        evidence: scene.evidenceManifest[0],
        hotspots: [
          {
            id: "desk",
            label: "Desk",
            sublocationId: "office",
            sublocationLabel: "Office",
          },
        ],
      },
      {
        evidence: scene.evidenceManifest[1],
        hotspots: [
          {
            id: "folder",
            label: "Folder",
            sublocationId: "office",
            sublocationLabel: "Office",
          },
        ],
      },
    ]);
  });
});

describe("moveEvidenceRevealInScene", () => {
  it("updates scene reveal arrays without dropping other reveal targets", () => {
    const updated = moveEvidenceRevealInScene(scene, "receipt", "folder");
    const desk = updated.sublocations[0].hotspots[0];
    const folder = updated.sublocations[0].hotspots[2];

    expect(desk.reveals).toEqual([
      { kind: "topic", characterId: "witness", topicId: "rain" },
    ]);
    expect(folder.reveals).toEqual([
      { kind: "evidence", id: "memo" },
      { kind: "evidence", id: "receipt" },
    ]);
  });
});
