// @vitest-environment jsdom

import { describe, expect, it, vi, beforeEach } from "vitest";
import type {
  InvestigationSceneJson,
  RectLayout,
  SpriteLayout,
} from "./layout-types";

vi.mock("@tauri-apps/api/core", () => ({
  invoke: vi.fn(),
}));

import { invoke } from "@tauri-apps/api/core";
import {
  editorState,
  setHotspotLayout,
  setCharacterLayout,
  loadChapters,
  loadInvestigationScene,
  assignEvidenceToCarrier,
  assignEvidenceToHotspot,
} from "./layout-store.svelte";

const mockInvoke = vi.mocked(invoke);

function resetState() {
  editorState.chapters = null;
  editorState.scene = null;
  editorState.layout = null;
  editorState.scenePath = null;
  editorState.layoutPath = null;
  editorState.storyScenePath = null;
  editorState.storySceneContents = null;
  editorState.error = null;
}

const carrierMarkdownForStoreTest = `# Investigation

## Sublocation: Inner {#inner}

### Hotspot: 法醫初步簡報 {#evidence_source_forensic_prelim_range}
- **Description:** 編輯器產生的隱藏證據來源。
- **Evidence Source:** hidden
- **Scene Source Prompt:** Hidden local evidence source generated by the layout editor; the collected evidence is not visibly readable in the background.
- **Reveals:** [evidence:forensic_prelim_range]

### Hotspot: 後場入口 {#back_entrance}
- **Description:** 後場入口。

### Character: 黑瀨 {#kurose}
- **Role:** 監察醫
- **Bio:** 冷靜而精準。

#### Topic: 法醫初步簡報 {#forensic_brief}
- **Status:** unlocked
`;

const topicCarrierMarkdownForStoreTest = `# Investigation

## Sublocation: Inner {#inner}

### Hotspot: 後場入口 {#back_entrance}
- **Description:** 後場入口。

### Character: 黑瀨 {#kurose}
- **Role:** 監察醫
- **Bio:** 冷靜而精準。

#### Topic: 法醫初步簡報 {#forensic_brief}
- **Status:** unlocked
- **Reveals:** [evidence:forensic_prelim_range]
`;

const sceneWithGeneratedForensicHotspotAndKuroseTopic = {
  type: "investigation",
  id: "investigation_scene_7",
  title: "Test Carrier Scene",
  intro: [],
  sublocations: [
    {
      id: "inner",
      label: "Inner",
      sceneTag: "Inner",
      backgroundAssetId: null,
      transitionDialogue: [],
      hotspots: [
        {
          id: "evidence_source_forensic_prelim_range",
          label: "法醫初步簡報",
          description: "編輯器產生的隱藏證據來源。",
          evidenceSource: "hidden",
          sceneSourcePrompt:
            "Hidden local evidence source generated by the layout editor; the collected evidence is not visibly readable in the background.",
          reveals: [{ kind: "evidence", id: "forensic_prelim_range" }],
          inspectDialogue: [],
          layout: null,
        },
        {
          id: "back_entrance",
          label: "後場入口",
          description: "後場入口。",
          evidenceSource: null,
          sceneSourcePrompt: null,
          reveals: [],
          inspectDialogue: [],
          layout: null,
        },
      ],
      characters: [
        {
          id: "kurose",
          name: "黑瀨",
          role: "監察醫",
          bio: "冷靜而精準。",
          layout: null,
          topics: [
            {
              id: "forensic_brief",
              label: "法醫初步簡報",
              topicDialogue: [],
              reveals: [],
            },
          ],
        },
      ],
    },
  ],
  evidenceManifest: [
    {
      id: "forensic_prelim_range",
      name: "法醫初步死亡範圍",
      description: "初步死亡時間範圍。",
      imageAssetId: null,
      sourceSublocationId: "inner",
    },
  ],
} satisfies InvestigationSceneJson;

const sceneWithForensicTopicReveal = {
  type: "investigation",
  id: "investigation_scene_8",
  title: "Test Standalone Carrier Scene",
  intro: [],
  sublocations: [
    {
      id: "inner",
      label: "Inner",
      sceneTag: "Inner",
      backgroundAssetId: null,
      transitionDialogue: [],
      hotspots: [
        {
          id: "back_entrance",
          label: "後場入口",
          description: "後場入口。",
          evidenceSource: null,
          sceneSourcePrompt: null,
          reveals: [],
          inspectDialogue: [],
          layout: null,
        },
      ],
      characters: [
        {
          id: "kurose",
          name: "黑瀨",
          role: "監察醫",
          bio: "冷靜而精準。",
          layout: null,
          topics: [
            {
              id: "forensic_brief",
              label: "法醫初步簡報",
              topicDialogue: [],
              reveals: [{ kind: "evidence", id: "forensic_prelim_range" }],
            },
          ],
        },
      ],
    },
  ],
  evidenceManifest: [
    {
      id: "forensic_prelim_range",
      name: "法醫初步死亡範圍",
      description: "初步死亡時間範圍。",
      imageAssetId: null,
      sourceSublocationId: "inner",
    },
  ],
} satisfies InvestigationSceneJson;

describe("layout-store", () => {
  beforeEach(() => {
    resetState();
    vi.clearAllMocks();
  });

  describe("setHotspotLayout", () => {
    it("sets a hotspot layout on an existing sublocation", () => {
      editorState.layout = {
        version: 1,
        sceneId: "scene_1",
        sublocations: {
          office: { hotspots: {}, characters: {} },
        },
      };

      const layout: RectLayout = {
        kind: "rect",
        x: 0.2,
        y: 0.3,
        w: 0.15,
        h: 0.1,
      };

      setHotspotLayout("office", "desk", layout);

      expect(editorState.layout?.sublocations.office.hotspots.desk).toEqual({
        kind: "rect",
        x: 0.2,
        y: 0.3,
        w: 0.15,
        h: 0.1,
      });
    });

    it("creates a new sublocation entry when none exists", () => {
      editorState.layout = {
        version: 1,
        sceneId: "scene_1",
        sublocations: {},
      };

      setHotspotLayout("lobby", "door", {
        kind: "rect",
        x: 0.5,
        y: 0.5,
        w: 0.1,
        h: 0.1,
      });

      expect(editorState.layout?.sublocations.lobby).toBeDefined();
      expect(
        editorState.layout?.sublocations.lobby.hotspots.door,
      ).toBeDefined();
    });

    it("preserves existing characters when setting a hotspot", () => {
      editorState.layout = {
        version: 1,
        sceneId: "scene_1",
        sublocations: {
          office: {
            hotspots: {},
            characters: {
              witness: {
                kind: "sprite",
                assetId: "standee.witness.standard",
                x: 0.5,
                y: 0.2,
                w: 0.2,
                h: 0.6,
                anchor: "bottomCenter",
              },
            },
          },
        },
      };

      setHotspotLayout("office", "desk", {
        kind: "rect",
        x: 0.1,
        y: 0.1,
        w: 0.1,
        h: 0.1,
      });

      expect(
        editorState.layout?.sublocations.office.characters.witness,
      ).toBeDefined();
    });

    it("does nothing when layout is null", () => {
      editorState.layout = null;

      setHotspotLayout("office", "desk", {
        kind: "rect",
        x: 0.5,
        y: 0.5,
        w: 0.1,
        h: 0.1,
      });

      expect(editorState.layout).toBeNull();
    });
  });

  describe("setCharacterLayout", () => {
    it("sets a character layout", () => {
      editorState.layout = {
        version: 1,
        sceneId: "scene_1",
        sublocations: {
          office: { hotspots: {}, characters: {} },
        },
      };

      const layout: SpriteLayout = {
        kind: "sprite",
        assetId: "standee.witness.standard",
        x: 0.6,
        y: 0.2,
        w: 0.18,
        h: 0.76,
        anchor: "bottomCenter",
      };

      setCharacterLayout("office", "witness", layout);

      const stored = editorState.layout?.sublocations.office.characters.witness;
      expect(stored).toEqual(layout);
    });

    it("clamps out-of-range values when setting a character layout", () => {
      editorState.layout = {
        version: 1,
        sceneId: "scene_1",
        sublocations: {
          office: { hotspots: {}, characters: {} },
        },
      };

      const outOfRange: SpriteLayout = {
        kind: "sprite",
        assetId: "standee.witness.standard",
        x: -0.5,
        y: 1.5,
        w: 0.0,
        h: 2.0,
        anchor: "bottomCenter",
      };

      setCharacterLayout("office", "witness", outOfRange);

      const stored = editorState.layout?.sublocations.office.characters.witness;
      expect(stored).not.toBeNull();
      expect(stored!.anchor).toBe("bottomCenter");
      expect(stored!.x).toBeGreaterThanOrEqual(0);
      expect(stored!.y).toBeGreaterThanOrEqual(0);
      expect(stored!.w).toBeGreaterThanOrEqual(0.025);
      expect(stored!.x + stored!.w).toBeLessThanOrEqual(1);
      expect(stored!.y + stored!.h).toBeLessThanOrEqual(1);
    });

    it("preserves existing hotspots when setting a character", () => {
      editorState.layout = {
        version: 1,
        sceneId: "scene_1",
        sublocations: {
          office: {
            hotspots: {
              desk: { kind: "rect", x: 0.1, y: 0.1, w: 0.1, h: 0.1 },
            },
            characters: {},
          },
        },
      };

      setCharacterLayout("office", "witness", {
        kind: "sprite",
        assetId: "standee.witness.standard",
        x: 0.5,
        y: 0.2,
        w: 0.2,
        h: 0.6,
        anchor: "bottomCenter",
      });

      expect(
        editorState.layout?.sublocations.office.hotspots.desk,
      ).toBeDefined();
    });
  });

  describe("loadInvestigationScene", () => {
    it("synthesizes empty layout when sidecar file is not found", async () => {
      const sceneJson = {
        type: "investigation",
        id: "scene_new",
        title: "New Scene",
        intro: [],
        sublocations: [],
        evidenceManifest: [],
      };

      mockInvoke
        .mockResolvedValueOnce({
          path: "scenes/scene_new.json",
          contents: JSON.stringify(sceneJson),
        })
        .mockResolvedValueOnce("layouts/scene_new.layout.json")
        .mockResolvedValueOnce(
          "docs/stories_plan/chapter_1/investigation_scene_1.md",
        )
        .mockResolvedValueOnce({
          path: "docs/stories_plan/chapter_1/investigation_scene_1.md",
          contents: "# Scene\n",
        })
        .mockRejectedValueOnce({ code: "notFound", message: "Not found" });

      await loadInvestigationScene("scenes/scene_new.json");

      expect(editorState.error).toBeNull();
      expect(editorState.scene?.id).toBe("scene_new");
      expect(editorState.layout).toEqual({
        version: 1,
        sceneId: "scene_new",
        sublocations: {},
      });
    });

    it("loads existing layout from sidecar file", async () => {
      const sceneJson = {
        type: "investigation",
        id: "scene_existing",
        title: "Existing Scene",
        intro: [],
        sublocations: [],
        evidenceManifest: [],
      };

      const existingLayout = {
        version: 1,
        sceneId: "scene_existing",
        sublocations: {
          office: {
            hotspots: {
              desk: { kind: "rect", x: 0.2, y: 0.3, w: 0.15, h: 0.1 },
            },
            characters: {},
          },
        },
      };

      mockInvoke
        .mockResolvedValueOnce({
          path: "scenes/scene_existing.json",
          contents: JSON.stringify(sceneJson),
        })
        .mockResolvedValueOnce("layouts/scene_existing.layout.json")
        .mockResolvedValueOnce(
          "docs/stories_plan/chapter_1/investigation_scene_existing.md",
        )
        .mockResolvedValueOnce({
          path: "docs/stories_plan/chapter_1/investigation_scene_existing.md",
          contents: "# Scene\n",
        })
        .mockResolvedValueOnce({
          path: "layouts/scene_existing.layout.json",
          contents: JSON.stringify(existingLayout),
        });

      await loadInvestigationScene("scenes/scene_existing.json");

      expect(editorState.error).toBeNull();
      expect(editorState.layout).toEqual(existingLayout);
    });

    it("surfaces non-notFound errors", async () => {
      mockInvoke.mockRejectedValueOnce({
        code: "permissionDenied",
        message: "Access denied",
      });

      await loadInvestigationScene("scenes/bad.json");

      expect(editorState.error).toBe("Access denied");
      expect(editorState.layout).toBeNull();
    });

    it("clears stale scene state when outer read fails", async () => {
      // First, populate state with a successful load
      const sceneJson = {
        type: "investigation",
        id: "scene_ok",
        title: "OK Scene",
        intro: [],
        sublocations: [],
        evidenceManifest: [],
      };
      mockInvoke
        .mockResolvedValueOnce({
          path: "scenes/scene_ok.json",
          contents: JSON.stringify(sceneJson),
        })
        .mockResolvedValueOnce("layouts/scene_ok.layout.json")
        .mockResolvedValueOnce(
          "docs/stories_plan/chapter_1/investigation_scene_ok.md",
        )
        .mockResolvedValueOnce({
          path: "docs/stories_plan/chapter_1/investigation_scene_ok.md",
          contents: "# Scene\n",
        })
        .mockResolvedValueOnce({
          path: "layouts/scene_ok.layout.json",
          contents: JSON.stringify({
            version: 1,
            sceneId: "scene_ok",
            sublocations: {},
          }),
        });

      await loadInvestigationScene("scenes/scene_ok.json");
      expect(editorState.scene?.id).toBe("scene_ok");
      expect(editorState.layoutPath).toBe("layouts/scene_ok.layout.json");
      expect(editorState.error).toBeNull();

      // Now fail a subsequent load — stale state must be cleared
      mockInvoke.mockRejectedValueOnce({
        code: "notFound",
        message: "Scene missing",
      });

      await loadInvestigationScene("scenes/missing.json");

      expect(editorState.error).toBe("Scene missing");
      expect(editorState.scene).toBeNull();
      expect(editorState.scenePath).toBeNull();
      expect(editorState.layout).toBeNull();
      expect(editorState.layoutPath).toBeNull();
      expect(editorState.storyScenePath).toBeNull();
      expect(editorState.storySceneContents).toBeNull();
    });
  });

  describe("assignEvidenceToHotspot", () => {
    it("assigns evidence to a topic and removes generated standalone layout", async () => {
      editorState.storyScenePath =
        "docs/stories_plan/chapter_1/investigation_scene_7.md";
      editorState.storySceneContents = carrierMarkdownForStoreTest;
      editorState.layout = {
        version: 1,
        sceneId: "investigation_scene_7",
        sublocations: {
          inner: {
            hotspots: {
              evidence_source_forensic_prelim_range: {
                kind: "rect",
                x: 0.4,
                y: 0.4,
                w: 0.12,
                h: 0.1,
              },
            },
            characters: {},
          },
        },
      };
      editorState.scene = sceneWithGeneratedForensicHotspotAndKuroseTopic;
      mockInvoke.mockResolvedValueOnce(undefined);

      await assignEvidenceToCarrier("forensic_prelim_range", {
        kind: "topic",
        sublocationId: "inner",
        characterId: "kurose",
        topicId: "forensic_brief",
      });

      expect(editorState.storySceneContents).toContain(
        "#### Topic: 法醫初步簡報 {#forensic_brief}\n- **Status:** unlocked\n- **Reveals:** [evidence:forensic_prelim_range]",
      );
      expect(
        editorState.layout?.sublocations.inner.hotspots
          .evidence_source_forensic_prelim_range,
      ).toBeUndefined();
      const kurose = editorState.scene.sublocations[0].characters[0];
      const forensicBrief = kurose.topics[0];
      expect(forensicBrief.reveals).toEqual([
        { kind: "evidence", id: "forensic_prelim_range" },
      ]);
    });

    it("assigns evidence to a standalone hotspot and clears the topic reveal", async () => {
      editorState.storyScenePath =
        "docs/stories_plan/chapter_1/investigation_scene_8.md";
      editorState.storySceneContents = topicCarrierMarkdownForStoreTest;
      editorState.layout = {
        version: 1,
        sceneId: "investigation_scene_8",
        sublocations: {
          inner: {
            hotspots: {},
            characters: {},
          },
        },
      };
      editorState.scene = sceneWithForensicTopicReveal;
      mockInvoke.mockResolvedValueOnce(undefined);

      await assignEvidenceToCarrier("forensic_prelim_range", {
        kind: "standalone_hotspot",
        sublocationId: "inner",
      });

      expect(editorState.storySceneContents).toContain(
        "### Hotspot: 法醫初步死亡範圍 {#evidence_source_forensic_prelim_range}\n- **Description:** 編輯器產生的隱藏證據來源。\n- **Evidence Source:** hidden\n- **Scene Source Prompt:** Hidden local evidence source generated by the layout editor; the collected evidence is not visibly readable in the background.\n- **Reveals:** [evidence:forensic_prelim_range]",
      );
      expect(editorState.storySceneContents).toContain(
        "#### Topic: 法醫初步簡報 {#forensic_brief}\n- **Status:** unlocked",
      );
      expect(editorState.storySceneContents).not.toContain(
        "#### Topic: 法醫初步簡報 {#forensic_brief}\n- **Status:** unlocked\n- **Reveals:** [evidence:forensic_prelim_range]",
      );

      const inner = editorState.scene.sublocations[0];
      const standaloneHotspot = inner.hotspots.find(
        (hotspot) => hotspot.id === "evidence_source_forensic_prelim_range",
      );
      expect(standaloneHotspot?.reveals).toEqual([
        { kind: "evidence", id: "forensic_prelim_range" },
      ]);
      const kurose = inner.characters[0];
      const forensicBrief = kurose.topics[0];
      expect(forensicBrief.reveals).toEqual([]);
    });

    it("writes authored markdown and updates the in-memory scene reveals", async () => {
      editorState.storyScenePath =
        "docs/stories_plan/chapter_1/investigation_scene_1.md";
      editorState.storySceneContents = `# Investigation

## Sublocation: Office {#office}

### Hotspot: Desk {#desk}
- **Description:** Desk.
- **Reveals:** [evidence:receipt]

### Hotspot: Terminal {#terminal}
- **Description:** Terminal.
`;
      editorState.scene = {
        type: "investigation",
        id: "investigation_scene_1",
        title: "Test",
        intro: [],
        sublocations: [
          {
            id: "office",
            label: "Office",
            sceneTag: "Office",
            backgroundAssetId: null,
            transitionDialogue: [],
            hotspots: [
              {
                id: "desk",
                label: "Desk",
                description: "Desk.",
                evidenceSource: null,
                sceneSourcePrompt: null,
                reveals: [{ kind: "evidence", id: "receipt" }],
                inspectDialogue: [],
                layout: null,
              },
              {
                id: "terminal",
                label: "Terminal",
                description: "Terminal.",
                evidenceSource: null,
                sceneSourcePrompt: null,
                reveals: [],
                inspectDialogue: [],
                layout: null,
              },
            ],
            characters: [],
          },
        ],
        evidenceManifest: [
          {
            id: "receipt",
            name: "Receipt",
            description: "Receipt clue.",
            imageAssetId: null,
            sourceSublocationId: null,
          },
        ],
      };
      mockInvoke.mockResolvedValueOnce(undefined);

      await assignEvidenceToHotspot("receipt", "terminal");

      expect(mockInvoke).toHaveBeenCalledWith("write_story_scene_file", {
        path: "docs/stories_plan/chapter_1/investigation_scene_1.md",
        contents: expect.stringContaining(
          "### Hotspot: Terminal {#terminal}\n- **Description:** Terminal.\n- **Reveals:** [evidence:receipt]",
        ),
      });
      expect(editorState.storySceneContents).toContain(
        "### Hotspot: Terminal {#terminal}\n- **Description:** Terminal.\n- **Reveals:** [evidence:receipt]",
      );
      expect(editorState.scene.sublocations[0].hotspots[0].reveals).toEqual([]);
      expect(editorState.scene.sublocations[0].hotspots[1].reveals).toEqual([
        { kind: "evidence", id: "receipt" },
      ]);
    });

    it("does not apply stale assignment results after the scene changes", async () => {
      editorState.storyScenePath =
        "docs/stories_plan/chapter_1/investigation_scene_1.md";
      editorState.storySceneContents = `# Investigation

## Sublocation: Office {#office}

### Hotspot: Desk {#desk}
- **Description:** Desk.
- **Reveals:** [evidence:receipt]

### Hotspot: Terminal {#terminal}
- **Description:** Terminal.
`;
      editorState.scene = {
        type: "investigation",
        id: "investigation_scene_1",
        title: "Scene A",
        intro: [],
        sublocations: [
          {
            id: "office",
            label: "Office",
            sceneTag: "Office",
            backgroundAssetId: null,
            transitionDialogue: [],
            hotspots: [
              {
                id: "desk",
                label: "Desk",
                description: "Desk.",
                evidenceSource: null,
                sceneSourcePrompt: null,
                reveals: [{ kind: "evidence", id: "receipt" }],
                inspectDialogue: [],
                layout: null,
              },
              {
                id: "terminal",
                label: "Terminal",
                description: "Terminal.",
                evidenceSource: null,
                sceneSourcePrompt: null,
                reveals: [],
                inspectDialogue: [],
                layout: null,
              },
            ],
            characters: [],
          },
        ],
        evidenceManifest: [
          {
            id: "receipt",
            name: "Receipt",
            description: "Receipt clue.",
            imageAssetId: null,
            sourceSublocationId: null,
          },
        ],
      };

      let finishWrite!: () => void;
      mockInvoke.mockReturnValueOnce(
        new Promise((resolve) => {
          finishWrite = () => resolve(undefined);
        }),
      );

      const assignment = assignEvidenceToHotspot("receipt", "terminal");

      const sceneB = {
        type: "investigation",
        id: "investigation_scene_2",
        title: "Scene B",
        intro: [],
        sublocations: [],
        evidenceManifest: [],
      } satisfies InvestigationSceneJson;
      editorState.storyScenePath =
        "docs/stories_plan/chapter_1/investigation_scene_2.md";
      editorState.storySceneContents = "# Scene B\n";
      editorState.scene = sceneB;

      finishWrite();
      await assignment;

      expect(editorState.storyScenePath).toBe(
        "docs/stories_plan/chapter_1/investigation_scene_2.md",
      );
      expect(editorState.storySceneContents).toBe("# Scene B\n");
      expect(editorState.scene?.id).toBe(sceneB.id);
      expect(editorState.scene?.sublocations).toEqual([]);
    });

    it("serializes same-scene assignments so stale writes cannot win", async () => {
      editorState.storyScenePath =
        "docs/stories_plan/chapter_1/investigation_scene_1.md";
      editorState.storySceneContents = `# Investigation

## Sublocation: Office {#office}

### Hotspot: Desk {#desk}
- **Description:** Desk.

### Hotspot: Terminal {#terminal}
- **Description:** Terminal.
`;
      editorState.scene = {
        type: "investigation",
        id: "investigation_scene_1",
        title: "Scene A",
        intro: [],
        sublocations: [
          {
            id: "office",
            label: "Office",
            sceneTag: "Office",
            backgroundAssetId: null,
            transitionDialogue: [],
            hotspots: [
              {
                id: "desk",
                label: "Desk",
                description: "Desk.",
                evidenceSource: null,
                sceneSourcePrompt: null,
                reveals: [],
                inspectDialogue: [],
                layout: null,
              },
              {
                id: "terminal",
                label: "Terminal",
                description: "Terminal.",
                evidenceSource: null,
                sceneSourcePrompt: null,
                reveals: [],
                inspectDialogue: [],
                layout: null,
              },
            ],
            characters: [],
          },
        ],
        evidenceManifest: [
          {
            id: "receipt",
            name: "Receipt",
            description: "Receipt clue.",
            imageAssetId: null,
            sourceSublocationId: null,
          },
        ],
      };

      const writes: Array<{
        contents: string;
        finish: () => void;
      }> = [];
      let persistedContents = editorState.storySceneContents;
      mockInvoke.mockImplementation((command, args) => {
        if (command !== "write_story_scene_file") {
          throw new Error(`Unexpected command: ${command}`);
        }

        return new Promise((resolve) => {
          writes.push({
            contents: (args as { contents: string }).contents,
            finish: () => {
              persistedContents = (args as { contents: string }).contents;
              resolve(undefined);
            },
          });
        });
      });

      const firstAssignment = assignEvidenceToHotspot("receipt", "terminal");
      const secondAssignment = assignEvidenceToHotspot("receipt", "desk");

      await vi.waitFor(() => expect(writes.length).toBeGreaterThan(0));

      if (writes.length === 2) {
        writes[1].finish();
        await secondAssignment;
        writes[0].finish();
      } else {
        writes[0].finish();
        await firstAssignment;
        if (writes.length === 2) {
          writes[1].finish();
        }
      }

      await Promise.all([firstAssignment, secondAssignment]);

      expect(persistedContents).toContain(
        "### Hotspot: Desk {#desk}\n- **Description:** Desk.\n- **Reveals:** [evidence:receipt]",
      );
      expect(persistedContents).not.toContain(
        "### Hotspot: Terminal {#terminal}\n- **Description:** Terminal.\n- **Reveals:** [evidence:receipt]",
      );
      expect(editorState.scene.sublocations[0].hotspots[0].reveals).toEqual([
        { kind: "evidence", id: "receipt" },
      ]);
      expect(editorState.scene.sublocations[0].hotspots[1].reveals).toEqual([]);
    });
  });

  describe("loadChapters", () => {
    it("clears stale chapters on read failure", async () => {
      // First, populate with a successful load
      mockInvoke.mockResolvedValueOnce({
        path: "chapters.json",
        contents: JSON.stringify({
          chapters: [{ id: "ch1", title: "Chapter 1", scenes: [] }],
        }),
      });

      await loadChapters();
      expect(editorState.chapters).not.toBeNull();
      expect(editorState.error).toBeNull();

      // Now fail a refresh — stale chapters must be cleared
      mockInvoke.mockRejectedValueOnce({
        code: "notFound",
        message: "File gone",
      });

      await loadChapters();

      expect(editorState.error).toBe("File gone");
      expect(editorState.chapters).toBeNull();
    });
  });
});
